spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apitestdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true